### ISSUE TITLE
tests - Add parsing tests

### ISSUE THREAD

**Issue by miracle2k** [ccxt/ccxt#3416]
After working on https://github.com/ccxt/ccxt/pull/3415 and others, I feel that the functions such as `parseTrade` or `parseOrder` have a lot of complexity in them. They have to deal with data formats that from different API calls that sometimes differ in their structure, and have to deal with various ifs and thens. Sometimes when making a change you have to worry that a certain special case is no longer properly handled.

Would do you think about having tests for these? I imagine a folder with test files, such as:

```
parser-tests/kraken/parseTrade-FromPublicApi.yaml
parser-tests/kraken/parseTrade-FromQueryTrades.yaml
...
```

YAML seems a suitable format because it is a superset of JSON, and also allows multiple documents per file. So ```parser-tests/kraken/parseTrade-FromQueryTrades.yaml```could look like this:

```yaml
{
    "ordertxid": "ONF74W-FMV7O-VP3T73",
    "postxid": "TKH2SE-M7IF5-CFI7LT",
    "pair": "EOSETH",
    "time": 1531156067.0903,
    "type": "buy",
    "ordertype": "limit",
    "price": "0.01775100",
    "cost": "0.37473528",
    "fee": "0.00097431",
    "vol": "21.11065729",
    "margin": "0.00000000",
    "misc": "",
    "id": "T2FARQ-AHBAH-AM7NMU"
}

---

{
    "id": "T2FARQ-AHBAH-AM7NMU",
    "order": "ONF74W-FMV7O-VP3T73",
    "timestamp": 1531156067090,
    "datetime": "2018-07-09T17:07:47.090Z",
    "symbol": "EOS/ETH",
    "type": "limit",
    "side": "buy",
    "price": 0.017751,
    "amount": 21.11065729,
    "cost": 0.37473527755478997,
    "fee": {
        "cost": 0.00097431,
        "currency": "ETH"
    }
}
```

The first document is the input, the second one is the output. To run these tests, we would loop over the files, run the input through the right function (say `parseTrade`), and ensure it matches the output. Because the test data is in JSON/YAML, they can be run in JS, but also in Python or PHP if desired.
